### ISSUE TITLE
[Crash]: Crash on Latest version of ATM9

### ISSUE THREAD

**Issue by zgrillo2004** [AllTheMods/ATM-9#2175]
### Possible Fixes

Yes

### Modpack Version

ATM9 1.0.0

### What happened?

I have a save that is pretty long. I have it backed up and it appears that it might be coming from PNC Repressuized. but how can that be because when I tried it on a new world, everything works fine. Not sure what to do.

### Crash Log

https://gist.github.com/zgrillo2004/7c9103d414b51ce399715e7417f68f94

### Latest.Log

https://gist.github.com/zgrillo2004/58855a572575ae09493dc813fce11d67

**Comment by yangywcz** [comment]
the same crash

**Comment by mutic0617** [comment]
me too..

**Comment by danny-janse** [comment]
If you're running into this issue, try downgrading pneumaticcraft to the previous version which can be found here [pneumaticcraft-repressurized-6.0.17+mc1.20.1.jar](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/files/5680613).

This should atleast rule out any crashes with pneumatic craft if not resolve any issues caused by the following pneumatic updates;
* Stopped the Pneumatic Armor Magnet upgrade working in spectator mode
* Drones no longer drop items with Vanishing Curse when they die
  * Exception: such items will still be dropped if the drone is wrenched by the owning player (and only the owning player)
* Fixed a race condition when using Computercraft to control Air Cannons

**Comment by T-LEstr** [comment]
> If you're running into this issue, try downgrading pneumaticcraft to the previous version which can be found here [pneumaticcraft-repressurized-6.0.17+mc1.20.1.jar](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/files/5680613).

This didn't work for me unfortunately, still the same crash.

**Comment by Mitchell5200** [comment]
Jebraltar has traced this to GTCeu, https://github.com/GregTechCEu/GregTech-Modern/issues/2644, and it will be fixed their side with PR https://github.com/GregTechCEu/GregTech-Modern/pull/2650, and the pack will be updated ASAP after that

**Comment by desht** [comment]
(PNC author) Thanks for tracking that down, I was a bit perturbed by the sudden flood of issues raised against PNC...
